name: Test if the code is working and is properly linted

on:
	pull_request:
		branches:
			- main
	workflow_dispatch:

jobs:
	test:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Install dependencies
				run: npm install

			- name: Run tests
				run: npm test

	lint:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Install dependencies
				run: npm install

			- name: Lint code
				run: npm run lint

